### ISSUE TITLE
Untracked files show up by default using git review

### ISSUE THREAD

**Issue by aabdala** [moliva/git-utils#1]
In my experience using git, many times I'm left with a lot of untracked files unrelated to the task at hand (for example switching between different branches with files left due to `.gitignore`). Having `git-review` include untracked files by default would be undesirable in most cases. 
On the other hand, when you check `git-status` you will realize how many untracked files there are and if your current intention includes checking some of them to add to the commit you may want to include those to the reviewing session (taking into account the proportion of untracked files related to the task against the total of them, maybe it's just one and you may prefer to do it manually).

A possible improvement could be adding a `git review -u` or `git review --review-untracked` kind of option, and not show untracked files by default.

**Comment by aabdala** [comment]
Another possible argument for changing the current behavior: most git commands do not act upon untracked files unless told to do so: `git commit -a`, `git diff`, `git stash`

**Comment by moliva** [comment]
Implemented! 😃
